### ISSUE TITLE
Term-04/satan/ has WAY too much reading material, and must be split into multiple courses and/or pruned to the most essential elements

### ISSUE THREAD

**Issue by JonathanMcCormickJr** [JonathanMcCormickJr/OSSP-CS#34]
Term-04/satan/ has WAY too much reading material, and must be split into multiple courses and/or pruned to the most essential elements

**Comment by LiberlandHacker** [comment]
Idea: Have ChatGPT input all existing reading materials and then suggest essential passages in order to maintain diversity of thought while still reducing the load of work to a manageable level.

**Comment by JonathanMcCormickJr** [comment]
No longer in-scope for term. Closing issue.
